### ISSUE TITLE
Collections Not Updating After Events

### ISSUE THREAD

**Issue by brandon-james105** [chris579/MvvmBlazor#12]
I have a subscription method event tied to collection management and a singleton collection storage object that calls the method. If I have two browser windows open, the event is fired in the window the item was created in but not the other one. I intended to get some effect like ASP.NET Core SignalR sockets realtime but was unable to get that effect. The list will only update if the user makes a change to the data in their own browser.

**Comment by chris579** [comment]
Could you also provide a small repro for this? Thanks!

**Comment by brandon-james105** [comment]
I'm unable to upload at this current time. I will make a repository and reference it here a couple hours from now. You should be able to clone that repo and check it out.

**Comment by brandon-james105** [comment]
I didn't mention that I am using Blazor server-side. I'm unable to upload at this current time. I will make a repository and reference it here a couple hours from now. You should be able to clone that repo and check it out.

**Comment by brandon-james105** [comment]
Okay, so on [the collection binding on this page](https://github.com/brandon-james105/BlazorPlanningPoker/blob/master/PlanningPoker/Pages/Sessions.razor#L26) which is stored in [the singleton registration](https://github.com/brandon-james105/BlazorPlanningPoker/blob/master/PlanningPoker/Startup.cs#L37) for this object [PlanningPokerSessionManager.cs](https://github.com/brandon-james105/BlazorPlanningPoker/blob/master/PlanningPoker/Services/PlanningPokerSessionManager.cs#L21) it won't update when you have two pages. This project got pulled straight from intranet so it uses Windows Authentication. You might not get it to work as is on Mac or Linux.

**Comment by brandon-james105** [comment]
The session manager fires an [event](https://github.com/brandon-james105/BlazorPlanningPoker/blob/master/PlanningPoker/ViewModels/SessionsViewModel.cs#L65), which appears to only be listened to by the window which caused the event, even though the session manager is a singleton.

**Comment by chris579** [comment]
That's interesting. Will look into that tomorrow.

**Comment by brandon-james105** [comment]
That would be great! This really is an interesting case. I was only able to get this to work before I included this library by including a StateChanged event handler which is triggered in any method I want in that session object. Then I used the InvokeAsync method in the Razor Page to call StateHasChanged in order to refresh the UI. That was just really inefficient and I want to use your library.

**Comment by chris579** [comment]
This problem is addressed in `v1.1.4` which has been pushed some seconds ago and is currently validated by NuGet.

**Comment by brandon-james105** [comment]
Thank you - this works, too. Collection Add/Remove works as intended. I appreciate all your work you put in today and so quickly after I filed the bugs.

However, one more thing - if you put viewmodels inside of observable collections, when they update they don't update in the UI. That's the only additional detail I could find for right now.

**Comment by chris579** [comment]
Could you create a new issue for that and provide a small repro? Thanks in advance!
