### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by pm64** [chris579/MvvmBlazor#29]
May I suggest starting a Gitter channel for MvvmBlazor? This is a remarkable library that I feel would benefit immensely from increased community engagement. Currently we're limited to this Issues page on Github, and perhaps Stackoverflow -- not ideal outlets for community discussion. I'd like to share my experiences with this library and see what others are doing.

**Comment by chris579** [comment]
Well, why not. [Here](https://gitter.im/MvvmBlazor/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) you go.
