### ISSUE TITLE
MVVMBlazor & UnitTest: how pass [Parameter] ?

### ISSUE THREAD

**Issue by gptucci** [chris579/MvvmBlazor#32]
Hi
Excuse my stupid question.
We are using TTD for a new project using MVVMBlazor. To test the View Models how can I pass the value for [Parameter] ?
Tnx

**Comment by chris579** [comment]
Well, as the property needs to have a public setting you can just use an object initializer or set the property after creating the view model.

```csharp
var vm = new MyViewModel
{
    MyParameter = "foo"
}
```
