### ISSUE TITLE
Possible issue with two-way binding of a component parameter

### ISSUE THREAD

**Issue by goldeneye9655** [chris579/MvvmBlazor#33]
I have a component that has a parameter:
```CSharp
[Parameter]
public bool Visible { get; set; }

[Parameter]
public EventCallback<bool> VisibleChanged { get; set; }
```
The `Visible` parameter is also defined in the ViewModel and properly passes in.

My issue is that I need that parameter to be a two-way binding:
```xml
<Component @bind-Visible="Visible" ... />
```

Am I setting this up wrong, or is this not possible?

**Comment by chris579** [comment]
I never tried a two way binding with a parameter.  
Your example shows a one way binding to the source (e.g. view model). The binding to the source is provided by Blazor itself.  
However, a binding to a component requires the use of the `Set` method as described [in the README](https://github.com/chris579/MvvmBlazor#property-implementation).

Using this property as a parameter should be possible. The parameter assignment happens before any lifecycle method and is also just using the ordinary setter of the property. So I don't see an issue there.
